services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:29092
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONNECTIONS_FROM_HOST://0.0.0.0:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"

  postgres:
    image: postgres:15.2
    restart: always
    env_file:
      - postgres.env
    environment:
       POSTGRES_DB: website_metrics
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: website_monitor_base
    entrypoint: /bin/true

  website_checker:
    build:
      context: .
      dockerfile: Dockerfile.website_checker
    volumes:
      - ./src/:/app/
      - ./tests:/app/tests
    depends_on:
      - kafka


  kafka_consumer_to_postgres:
    build:
      context: .
      dockerfile: Dockerfile.kafka_to_postgres
    env_file:
      - postgres.env
    volumes:
      - ./src/:/app/
      - ./tests:/app/tests
    depends_on:
      - postgres
      - kafka
      - website_checker