# Configuration settings for WebsiteAvailabilityMonitor

producer_interval: 15
timeout: 10

# Kafka settings
kafka:
  bootstrap_servers: kafka:9092
  topic: website_metrics

# PostgreSQL settings
database:
  dsn: "postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@postgres:5432/website_metrics"

# List of target websites and their monitoring settings
websites:
  - url: https://google.com
  - url: https://lichess.org
    regexp: Lichess is open source