# Configuration settings for WebsiteAvailabilityMonitor

producer_interval: 15
timeout: 10

# Kafka settings
kafka:
  bootstrap_servers: {KAFKA_HOST}:{KAFKA_PORT}
  topic: {KAFKA_TOPIC}
  security_protocol: PLAINTEXT  # PLAINTEXT or SSL

# PostgreSQL settings
database:
  dsn: "postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

# List of target websites and their monitoring settings
websites:
  - url: https://google.com
  - url: https://lichess.org
    regexp: Lichess is open source