# Configuration settings for WebsiteAvailabilityMonitor

producer_interval: 60

# Kafka settings
kafka:
  bootstrap_servers: localhost:29092
  topic: website_metrics

# PostgreSQL settings
postgres:
  dsn: "postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@localhost:5432/website_metrics"

# List of target websites and their monitoring settings
websites:
  - url: https://google.com
  - url: https://lichess.org
    regexp: Lichess is open source